name: my-check

on: push

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      # Node versions list
      matrix:
        node-version: [ 20.x ]

    steps:
      - name: test and lint
        uses: actions/checkout@v4
      - run: make install
      - run: make lint
      - run: make test
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v5.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: npm test -- --coverage --coverageProvider=v8
          debug: true